FROM postgres:13

# Copy custom configuration files
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Set environment variables to use custom configuration
ENV POSTGRES_CONFIG_FILE=/etc/postgresql/postgresql.conf

# Optionally, add initialization scripts
COPY initdb /docker-entrypoint-initdb.d/