version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: My1Hard2Guess3Password4
      POSTGRES_DB: prayer_app_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  web:
    build: .
    container_name: my_flask_app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:My1Hard2Guess3Password4@db:5432/prayer_app_database
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
