services:
  - type: web
    name: flask-prayer-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    releaseCommand: flask db upgrade
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prayer-db
          property: connectionString

databases:
  - name: prayer-db
    plan: free
